### ISSUE TITLE
Dataproc startup borked - trailing slash

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/cpg-utils#157]
https://github.com/populationgenomics/cpg-utils/blob/b42013b75e6812335a11ba1201cd2b9f495a4fa9/cpg_utils/dataproc.py#L284-L297

see https://batch.hail.populationgenomics.org.au/batches/442999/jobs/90

This join onto an empty String results in a trailing slash

```
>>> dataset_path('', 'tmp').split('://')[1]
'cpg-PROJECT-main-tmp/'
```

This is not tolerated during dataproc startup:

```
ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Storage Bucket name 'cpg-PROJECT-main-tmp/' must match pattern '[a-z0-9\-_.]{3,222}'
```

## proposal

remove the dataset-path call with

```
get_config()['storage']['default']['tmp'].removeprefix('gs://')
```

This would also solve the production-pipelines test use-case - config files are generated during tests, having tmp-dir test paths embedded as storage options (these do not start with `gs://`). I patched this [here](https://github.com/populationgenomics/production-pipelines/pull/690/commits/3c9188e9d8095632b113fbd3fa635c6d90cdf409) to get the test suite running, but a change in this lib would make that unnecessary.

**Comment by EddieLF** [comment]
We could use the new `config_retrieve` function like `config_retrieve(['storage', 'default', 'tmp'])` to get the bucket name
