### ISSUE TITLE
Migrate git.py from analysis-runner to cpg-utils

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/cpg-utils#23]
The git.py code from analysis-runner (https://github.com/populationgenomics/analysis-runner/blob/main/analysis_runner/git.py) contains helpful functionality for cloning and managing git repositories within hail batches. To cut the dependency on analysis-runner, migrate that functionality into this repository. 

Changes: 
- remove organisation lock to `populationgenomics`?
- remove the in-container failure for the commit being on main?
- remove lock to single key file location

**Comment by lgruen** [comment]
@illusional FYI

> remove lock to single key file location

Do you mean `/gsa-key/key.json`? That's actually based on a Hail Batch convention, but we'll need to adapt that to support Azure anyway (also see https://centrepopgen.slack.com/archives/C018KFBCR1C/p1648708418333029?thread_ts=1648693315.671699&cid=C018KFBCR1C).

**Comment by MattWellie** [comment]
@lgruen Yeah, I was assuming the key could be in different locations so I've stripped GOOGLE from the name, and allowed the location to be overwritten (hail batch location by default)
